--- MakefileTWO	2017-05-08 21:52:14.745359767 -0700
+++ Makefile	2017-05-08 17:31:58.018503805 -0700
@@ -1,13 +1,13 @@
 #
-## Makefile for the kernel block layer
+# Makefile for the kernel block layer
 #
 
 obj-$(CONFIG_BLOCK) := elevator.o blk-core.o blk-tag.o blk-sysfs.o \
-   blk-flush.o blk-settings.o blk-ioc.o blk-map.o \
-   blk-exec.o blk-merge.o blk-softirq.o blk-timeout.o \
-   blk-iopoll.o blk-lib.o blk-mq.o blk-mq-tag.o \
-   blk-mq-sysfs.o blk-mq-cpu.o blk-mq-cpumap.o ioctl.o \
-   genhd.o scsi_ioctl.o partition-generic.o partitions/
+			blk-flush.o blk-settings.o blk-ioc.o blk-map.o \
+			blk-exec.o blk-merge.o blk-softirq.o blk-timeout.o \
+			blk-iopoll.o blk-lib.o blk-mq.o blk-mq-tag.o \
+			blk-mq-sysfs.o blk-mq-cpu.o blk-mq-cpumap.o ioctl.o \
+			genhd.o scsi_ioctl.o partition-generic.o partitions/
 
 obj-$(CONFIG_BLK_DEV_BSG)	+= bsg.o
 obj-$(CONFIG_BLK_DEV_BSGLIB)	+= bsg-lib.o
@@ -16,7 +16,8 @@
 obj-$(CONFIG_IOSCHED_NOOP)	+= noop-iosched.o
 obj-$(CONFIG_IOSCHED_DEADLINE)	+= deadline-iosched.o
 obj-$(CONFIG_IOSCHED_CFQ)	+= cfq-iosched.o
+obj-$(CONFIG_IOSCHED_CLOOK)	+= clook-iosched.o
 
 obj-$(CONFIG_BLOCK_COMPAT)	+= compat_ioctl.o
 obj-$(CONFIG_BLK_DEV_INTEGRITY)	+= blk-integrity.o
-obj-$(CONFIG_BLK_CMDLINE_PARSER)	+= cmdline-parser.o)))))))))))
+obj-$(CONFIG_BLK_CMDLINE_PARSER)	+= cmdline-parser.o
